
[functions.upload-abstract]
enabled = true
verify_jwt = false
import_map = "./functions/upload-abstract/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/upload-abstract/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/upload-abstract/*.html" ]

[functions.get-abstract-url]
enabled = true
verify_jwt = true
import_map = "./functions/get-abstract-url/deno.json"
entrypoint = "./functions/get-abstract-url/index.ts"

[functions.shortlisted-teams]
enabled     = true
verify_jwt  = false
import_map  = "./functions/shortlisted-teams/deno.json"
entrypoint  = "./functions/shortlisted-teams/index.ts"

[functions.validate-team]
enabled    = true
verify_jwt = false
import_map = "./functions/validate-team/deno.json"
entrypoint = "./functions/validate-team/index.ts"

[functions.create-payment-order]
enabled    = true
verify_jwt = false
import_map = "./functions/create-payment-order/deno.json"
entrypoint = "./functions/create-payment-order/index.ts"

[functions.payment-callback]
enabled    = true
verify_jwt = false
import_map = "./functions/payment-callback/deno.json"
entrypoint = "./functions/payment-callback/index.ts"

[functions.sync-sheet]
enabled    = true
verify_jwt = true
import_map = "./functions/sync-sheet/deno.json"
entrypoint = "./functions/sync-sheet/index.ts"
