export const FRAMES = [
  {
    id: 'classic',
    name: 'Classic',
    description: 'Warm white paper',
    paper: '#F2EEE4',
    ink: '#0F172A',
    mutedInk: '#475569',
    hashtagColor: '#000000',
    motifIndigo: '#3730A3',
    motifViolet: '#6D28D9',
    motifCyan: '#0369A1',
    logoFilter: 'none',
    isDark: false,
    grain: 'multiply',
  },
  {
    id: 'midnight',
    name: 'Midnight',
    description: 'Deep black polaroid',
    paper: '#111216',
    ink: '#FFFFFF',
    mutedInk: '#94A3B8',
    hashtagColor: '#FFFFFF',
    motifIndigo: '#C4B5FD',
    motifViolet: '#E9D5FF',
    motifCyan: '#A5F3FC',
    logoFilter: 'brightness(0) invert(1)',
    isDark: true,
    grain: 'screen',
  },
  {
    id: 'burgundy',
    name: 'Burgundy',
    description: 'Deep wine velvet',
    paper: '#4A1521',
    ink: '#FFF7ED',
    mutedInk: '#F5D9D0',
    hashtagColor: '#FFF7ED',
    motifIndigo: '#F5C2D0',
    motifViolet: '#F4D5E4',
    motifCyan: '#C8E4E6',
    logoFilter: 'brightness(0) invert(1)',
    isDark: true,
    grain: 'screen',
  },
  {
    id: 'slate',
    name: 'Dusty Slate Blue',
    description: 'Dusty slate paper',
    paper: '#334155',
    ink: '#F8FAFC',
    mutedInk: '#CBD5E1',
    hashtagColor: '#F8FAFC',
    motifIndigo: '#CBD5E1',
    motifViolet: '#E2E8F0',
    motifCyan: '#38BDF8',
    logoFilter: 'brightness(0) invert(1)',
    isDark: true,
    grain: 'screen',
  },
  {
    id: 'gold',
    name: 'Antique Gold',
    description: 'Rich antique brass paper',
    paper: '#8B6F2E',
    ink: '#1A1408',
    mutedInk: '#362A10',
    hashtagColor: '#000000',
    motifIndigo: '#3E2A0E',
    motifViolet: '#523A13',
    motifCyan: '#1A3837',
    logoFilter: 'brightness(0)',
    isDark: false,
    grain: 'multiply',
  },
];

export const DEFAULT_FRAME = FRAMES[0];
export function getFrame(frameId) {
  return FRAMES.find((frame) => frame.id === frameId) ?? DEFAULT_FRAME;
}

